/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
static yyconst short int yy_accept[291] =
    {   0,
       56,   56,   60,   59,   57,   58,   59,   59,   59,   49,
       50,   33,   31,   32,   34,   56,   53,   38,   30,   39,
       59,   54,   51,   52,   35,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   47,   59,   48,   59,   43,   44,
        0,    0,   36,   37,    0,   56,   40,    0,   41,   16,
       54,   54,   54,   54,   54,   54,   54,   25,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   45,   46,    0,
        0,    0,    0,    0,    0,    0,   55,   42,   54,   54,
       54,   22,   54,   54,   54,   28,   54,   17,   23,   24,
       54,   54,   21,   54,   54,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       19,   54,    0,    0,   26,   27,   54,    0,   54,   17,
        0,    0,   54,    0,    0,    0,    0,   54,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    3,    3,    0,    0,    0,    0,    0,    0,    3,
        3,    0,    0,    0,    0,    0,    0,    0,    4,    4,
        0,   19,   20,    0,    0,    0,   18,    0,    0,   54,
        0,    0,    0,    0,   54,    0,    0,    0,    0,    0,
        0,   29,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    3,    3,    0,    0,    0,    0,

        0,    0,    5,    5,    0,    0,    3,    3,    0,    0,
        5,    5,    0,    0,    4,    4,    0,    0,    6,    6,
        0,   20,   11,    0,   18,    0,    0,   54,    0,    0,
        0,    0,    0,    0,   12,    0,   13,    0,    0,    2,
        2,    0,    0,    0,    0,    1,    1,    0,    0,    1,
        1,    0,    0,    1,    1,    0,    0,    0,   14,   15,
        0,    0,    0,    0,    0,    0,    0,    0,    8,    0,
        0,    0,    0,    0,    9,    0,    0,    0,   10,    0,
        0,    0,   10,    0,    0,    0,    0,    0,    7,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    1,    1,    1,    1,    5,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,   20,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       22,    1,   23,   24,   25,    1,   26,   27,   28,   21,

       29,   30,   21,   31,   32,   21,   21,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   21,   43,   44,
       21,   21,   45,   46,   47,   48,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[49] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    5,    1,    1,
        1,    1,    6,    1,    7,    1,    3,    8,    3,    1,
        9,    1,    1,    1,   10,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[330] =
    {   0,
        0,    0,  686,  943,  943,  943,  662,  674,   46,   47,
      943,  943,  668,  664,  943,   41,  943,  654,  653,  652,
      648,    0,  943,  943,  943,   24,  631,   25,   29,   25,
      624,   30,  636,  623,  943,  607,  943,  599,  943,  943,
       64,   68,  943,  943,  629,   60,  943,  625,  943,  943,
        0,  616,   41,  614,   37,  603,  597,    0,  598,  592,
      586,  592,  589,  581,  574,  577,  552,  943,  943,   76,
       84,   93,   97,   86,   99,  103,  568,  943,  543,  540,
       95,    0,  549,  549,  551,   77,  540,  552,  546,  545,
      515,  115,    0,  116,  506,  120,  124,  125,  129,  131,

      147,  133,  151,  153,  155,  102,  159,  161,  163,  165,
      534,  476,  137,  130,    0,    0,  470,  169,  419,  452,
      159,  165,  409,  175,  171,  178,  175,  414,  181,  185,
      189,  193,  198,  202,  210,  219,  211,  212,  220,  228,
      229,  236,  943,  237,  243,  244,  245,  250,  251,  257,
      943,  258,  264,  265,  266,  270,  272,  278,  282,  943,
      286,  433,  419,  399,  192,  400,  398,  290,  292,  346,
      247,  183,  289,  268,  296,  352,  292,  344,  328,  293,
      334,    0,  303,  307,  308,  312,  316,  320,  323,  325,
      329,  337,  342,  343,  350,  943,  351,  357,  358,  359,

      363,  364,  375,  943,  376,  382,  383,  943,  389,  390,
      396,  943,  397,  403,  404,  943,  410,  411,  417,  943,
      418,  333,  943,  326,  322,  424,  425,  274,  225,  297,
      217,  365,  426,  456,  943,  216,  943,  201,  431,  432,
      943,  438,  501,  502,  439,  445,  943,  446,  506,  507,
      943,  515,  519,  523,  943,  527,  153,  157,  943,  943,
      530,  136,  526,  560,  536,  602,  112,   97,    0,    0,
      603,  513,   76,   78,    0,  604,  607,  276,   75,  617,
      608,  306,   62,  611,  614,  540,  371,  541,  943,  943,
      636,  639,  648,  657,  665,  673,  681,  689,  697,  706,

      714,  722,  731,  739,  747,  753,  761,  766,  771,  779,
      787,  795,  803,  812,  820,  829,  838,  847,  856,  862,
      871,  877,  883,  892,  901,  910,  919,  928,  932
    } ;

static yyconst short int yy_def[330] =
    {   0,
      290,    1,  290,  290,  290,  290,  290,  290,  291,  291,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  292,  290,  290,  290,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  290,  290,  290,  290,  290,  290,
      291,  293,  290,  290,  290,  290,  290,  290,  290,  290,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  290,  290,  290,
      290,  294,  293,  295,  290,  296,  290,  290,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  290,  294,  290,  297,  298,

      299,  295,  300,  301,  302,  290,  296,  303,  304,  305,
      292,  292,  290,  306,  292,  292,  292,  307,  292,  290,
      290,  290,  292,  290,  308,  290,  309,  292,  310,   97,
      310,  297,  310,  311,  312,  313,  298,  312,  314,  315,
      290,  290,  290,  299,  300,  316,  301,  317,  290,  290,
      290,  302,  314,  303,  318,  304,  319,  290,  290,  290,
      305,  290,  292,  290,  290,  320,  292,  307,  321,  292,
      290,  290,  290,  290,  292,  290,  290,  322,  290,  290,
      323,  292,  310,  324,  310,  132,  310,  311,  188,  325,
      312,  312,  326,  290,  290,  290,  313,  312,  314,  314,

      327,  290,  290,  290,  315,  290,  290,  290,  316,  290,
      290,  290,  317,  290,  290,  290,  318,  290,  290,  290,
      319,  290,  290,  320,  290,  290,  321,  292,  290,  290,
      290,  290,  290,  290,  290,  322,  290,  323,  290,  290,
      290,  324,  132,  188,  290,  290,  290,  325,  290,  290,
      290,  326,  290,  290,  290,  327,  290,  328,  290,  290,
      234,  261,  261,  234,  188,  290,  329,  261,  261,  264,
      290,  290,  290,  329,  261,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,    0,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290
    } ;

static yyconst short int yy_nxt[992] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
        4,   14,    4,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,    4,   22,   22,   26,   27,   28,
       22,   29,   22,   30,   22,   22,   31,   22,   22,   32,
       33,   22,   34,   22,   35,   36,   37,   38,   41,   41,
       61,   41,   41,   45,   52,   46,   62,   56,   58,   53,
       57,   64,   59,   60,  283,   54,   41,   65,   83,   41,
       70,   71,   45,   72,   46,   80,   84,  283,   70,   71,
       81,   72,  118,  118,   74,   75,   76,   96,  102,   96,
      273,  103,   74,   75,   76,   97,   98,  113,   99,   70,

       71,  114,   72,  104,  106,  107,  279,  153,  108,   74,
      100,   76,  275,   74,   75,   76,  106,  124,  126,  153,
      109,  125,  127,  129,  273,  129,   97,   71,  131,  130,
      131,  132,  133,  137,  134,  102,  138,  164,  102,  113,
       74,   75,   76,  114,  165,   74,  135,   76,  139,  141,
      290,  269,  142,  145,  143,  147,  145,  149,  147,  258,
      150,  107,  151,  154,  107,  156,  154,  158,  156,  171,
      159,  168,  160,  172,  168,  173,  290,  124,  176,  174,
      126,  125,  179,  183,  127,  177,  183,  266,   98,  180,
       99,  183,  129,  171,  185,  132,   71,  172,  186,  164,

      183,  131,  100,  187,  188,  133,  165,  189,  179,   74,
       75,   76,  191,  137,  191,  192,  137,  198,   74,  135,
       76,  194,  199,  176,  195,  200,  196,  139,  290,  153,
      202,  141,  260,  203,  142,  204,  143,  153,  141,  141,
      259,  142,  142,  143,  143,  145,  206,  147,  145,  207,
      147,  208,  210,  149,  229,  211,  150,  212,  151,  149,
      149,  230,  150,  150,  151,  151,  199,  154,  214,  199,
      154,  215,  156,  216,  218,  156,  258,  219,  173,  220,
      158,  290,  174,  159,  158,  160,  277,  159,  158,  160,
      278,  159,  168,  160,  226,  168,  231,  226,  233,  176,

      179,  234,  234,  232,  229,  183,  177,  180,  183,  239,
      183,  230,  240,  183,  241,   98,  281,  243,  183,  129,
      282,  185,  188,   71,  225,  244,  133,  245,  189,  100,
      246,  191,  247,  164,  191,  222,   74,   75,   76,  191,
      135,  179,  198,  237,  249,  194,  290,  250,  195,  251,
      196,  176,  194,  194,  153,  195,  195,  196,  196,  191,
      199,  199,  191,  199,  199,  253,  202,  235,  254,  203,
      255,  204,  231,  287,  290,  290,  290,  202,  202,  232,
      203,  203,  204,  204,  206,  206,  228,  207,  207,  208,
      208,  206,  210,  286,  207,  211,  208,  212,  210,  210,

      225,  211,  211,  212,  212,  214,  214,  164,  215,  215,
      216,  216,  214,  218,  223,  215,  219,  216,  220,  218,
      218,  222,  219,  219,  220,  220,  226,  226,  233,  226,
      226,  234,  234,  239,  239,  162,  240,  240,  241,  241,
      239,  245,  182,  240,  246,  241,  247,  245,  245,  175,
      246,  246,  247,  247,  120,  257,  261,  170,  261,  261,
      261,  262,  261,  262,  261,  261,  261,  261,  261,  261,
      263,  261,  261,  261,  261,  261,  264,  261,  261,  261,
      261,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      261,  261,  261,  261,  133,   98,  134,  265,  249,  249,
      167,  250,  250,  251,  251,  276,  163,  249,  135,  100,
      250,  253,  251,  277,  254,  253,  255,  278,  254,  253,
      255,  262,  254,  262,  255,  268,  162,  268,  128,  133,
      263,  189,  288,  288,  261,  289,  289,  289,  289,  123,
      261,  122,  121,  135,  120,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  270,  119,  117,  116,  115,  112,
      270,  111,   77,   95,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  271,  271,  276,  271,  271,  280,
      284,   94,   93,  284,  277,   92,  287,  281,  278,  280,
       91,  282,  285,  272,  272,  285,   90,  281,  285,   89,
      286,  282,   88,  286,   87,   86,  286,   42,   85,   42,
       82,   79,   78,   77,   42,   51,   69,   51,   51,   73,
       73,   73,   68,   67,   73,   73,   73,   73,  101,  101,
      101,   66,   63,   55,  101,  101,  105,   50,  105,   49,
       48,   47,  105,  105,  110,   44,  110,   43,   40,   39,
      110,  110,  136,  136,  136,  290,  290,  290,  136,  136,
      140,  290,  140,  290,  290,  290,  140,  140,  144,  290,

      144,  144,  290,  144,  290,  144,  144,  146,  290,  146,
      290,  290,  290,  290,  146,  148,  290,  148,  290,  290,
      290,  290,  148,  152,  290,  152,  152,  290,  152,  290,
      152,  152,  155,  290,  155,  290,  290,  290,  290,  155,
      157,  290,  157,  290,  290,  290,  290,  157,  161,  290,
      161,  161,  290,  161,  290,  161,  161,  166,  290,  166,
      290,  166,  169,  290,  169,  290,  290,  290,  290,  169,
      178,  290,  178,  290,  178,  181,  290,  181,  290,  181,
      184,  290,  184,  290,  290,  290,  290,  184,  190,  190,
      190,  290,  290,  290,  190,  190,  193,  290,  193,  290,

      290,  290,  193,  193,  197,  290,  197,  197,  290,  197,
      290,  197,  197,  201,  290,  201,  290,  290,  290,  201,
      201,  205,  290,  205,  205,  290,  205,  290,  205,  205,
      209,  290,  209,  209,  290,  209,  290,  209,  209,  213,
      290,  213,  213,  290,  213,  290,  213,  213,  217,  290,
      217,  217,  290,  217,  290,  217,  217,  221,  290,  221,
      221,  290,  221,  290,  221,  221,  224,  290,  224,  290,
      224,  224,  227,  290,  227,  290,  290,  227,  290,  227,
      227,  236,  290,  236,  290,  236,  236,  238,  290,  238,
      290,  238,  238,  242,  290,  242,  242,  290,  242,  290,

      242,  242,  248,  290,  248,  248,  290,  248,  290,  248,
      248,  252,  290,  252,  252,  290,  252,  290,  252,  252,
      256,  290,  256,  256,  290,  256,  290,  256,  256,  267,
      290,  290,  290,  290,  290,  290,  267,  274,  274,  290,
      274,  274,    3,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290

    } ;

static yyconst short int yy_chk[992] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   10,
       30,    9,   10,   16,   26,   16,   30,   28,   29,   26,
       28,   32,   29,   29,  283,   26,   41,   32,   55,   41,
       42,   42,   46,   42,   46,   53,   55,  279,   70,   70,
       53,   70,   86,   86,   42,   42,   42,   71,   74,   71,
      274,   74,   70,   70,   70,   72,   72,   81,   72,   73,

       73,   81,   73,   74,   75,   76,  273,  106,   76,   72,
       72,   72,  268,   73,   73,   73,   75,   92,   94,  106,
       76,   92,   94,   96,  267,   96,   97,   97,   98,   97,
       98,   99,   99,  100,   99,  102,  100,  114,  102,  113,
       97,   97,   97,  113,  114,   99,   99,   99,  100,  101,
      102,  262,  101,  103,  101,  104,  103,  105,  104,  258,
      105,  107,  105,  108,  107,  109,  108,  110,  109,  121,
      110,  118,  110,  121,  118,  122,  107,  124,  125,  122,
      126,  124,  127,  129,  126,  125,  129,  257,  130,  127,
      130,  131,  131,  172,  131,  132,  132,  172,  132,  165,

      133,  133,  130,  133,  134,  134,  165,  134,  238,  132,
      132,  132,  135,  137,  138,  135,  137,  138,  134,  134,
      134,  136,  139,  236,  136,  139,  136,  135,  137,  138,
      140,  141,  231,  140,  141,  140,  141,  139,  142,  144,
      229,  142,  144,  142,  144,  145,  146,  147,  145,  146,
      147,  146,  148,  149,  171,  148,  149,  148,  149,  150,
      152,  171,  150,  152,  150,  152,  153,  154,  155,  153,
      154,  155,  156,  155,  157,  156,  228,  157,  174,  157,
      158,  153,  174,  158,  159,  158,  278,  159,  161,  159,
      278,  161,  168,  161,  169,  168,  173,  169,  175,  177,

      180,  175,  175,  173,  230,  183,  177,  180,  183,  184,
      185,  230,  184,  185,  184,  186,  282,  186,  187,  187,
      282,  187,  188,  188,  225,  188,  189,  190,  189,  186,
      190,  191,  190,  224,  191,  222,  188,  188,  188,  192,
      189,  181,  192,  179,  193,  194,  191,  193,  194,  193,
      194,  178,  195,  197,  192,  195,  197,  195,  197,  198,
      199,  200,  198,  199,  200,  201,  202,  176,  201,  202,
      201,  202,  232,  287,  198,  199,  200,  203,  205,  232,
      203,  205,  203,  205,  206,  207,  170,  206,  207,  206,
      207,  209,  210,  287,  209,  210,  209,  210,  211,  213,

      167,  211,  213,  211,  213,  214,  215,  166,  214,  215,
      214,  215,  217,  218,  164,  217,  218,  217,  218,  219,
      221,  163,  219,  221,  219,  221,  226,  227,  233,  226,
      227,  233,  233,  239,  240,  162,  239,  240,  239,  240,
      242,  245,  128,  242,  245,  242,  245,  246,  248,  123,
      246,  248,  246,  248,  120,  226,  234,  119,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,

      234,  234,  234,  234,  243,  244,  243,  244,  249,  250,
      117,  249,  250,  249,  250,  272,  112,  252,  243,  244,
      252,  253,  252,  272,  253,  254,  253,  272,  254,  256,
      254,  263,  256,  263,  256,  261,  111,  261,   95,  265,
      263,  265,  286,  288,  261,  286,  288,  286,  288,   91,
      261,   90,   89,  265,   88,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  264,   87,   85,   84,   83,   80,
      264,   79,   77,   67,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  266,  271,  276,  266,  271,  277,
      281,   66,   65,  284,  276,   64,  285,  277,  276,  280,
       63,  277,  281,  266,  271,  284,   62,  280,  285,   61,
      281,  280,   60,  284,   59,   57,  285,  291,   56,  291,
       54,   52,   48,   45,  291,  292,   38,  292,  292,  293,
      293,  293,   36,   34,  293,  293,  293,  293,  294,  294,
      294,   33,   31,   27,  294,  294,  295,   21,  295,   20,
       19,   18,  295,  295,  296,   14,  296,   13,    8,    7,
      296,  296,  297,  297,  297,    3,    0,    0,  297,  297,
      298,    0,  298,    0,    0,    0,  298,  298,  299,    0,

      299,  299,    0,  299,    0,  299,  299,  300,    0,  300,
        0,    0,    0,    0,  300,  301,    0,  301,    0,    0,
        0,    0,  301,  302,    0,  302,  302,    0,  302,    0,
      302,  302,  303,    0,  303,    0,    0,    0,    0,  303,
      304,    0,  304,    0,    0,    0,    0,  304,  305,    0,
      305,  305,    0,  305,    0,  305,  305,  306,    0,  306,
        0,  306,  307,    0,  307,    0,    0,    0,    0,  307,
      308,    0,  308,    0,  308,  309,    0,  309,    0,  309,
      310,    0,  310,    0,    0,    0,    0,  310,  311,  311,
      311,    0,    0,    0,  311,  311,  312,    0,  312,    0,

        0,    0,  312,  312,  313,    0,  313,  313,    0,  313,
        0,  313,  313,  314,    0,  314,    0,    0,    0,  314,
      314,  315,    0,  315,  315,    0,  315,    0,  315,  315,
      316,    0,  316,  316,    0,  316,    0,  316,  316,  317,
        0,  317,  317,    0,  317,    0,  317,  317,  318,    0,
      318,  318,    0,  318,    0,  318,  318,  319,    0,  319,
      319,    0,  319,    0,  319,  319,  320,    0,  320,    0,
      320,  320,  321,    0,  321,    0,    0,  321,    0,  321,
      321,  322,    0,  322,    0,  322,  322,  323,    0,  323,
        0,  323,  323,  324,    0,  324,  324,    0,  324,    0,

      324,  324,  325,    0,  325,  325,    0,  325,    0,  325,
      325,  326,    0,  326,  326,    0,  326,    0,  326,  326,
      327,    0,  327,  327,    0,  327,    0,  327,  327,  328,
        0,    0,    0,    0,    0,    0,  328,  329,  329,    0,
      329,  329,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1807053.l"
#define INITIAL 0
#line 2 "1807053.l"
    #include<stdio.h>
	#include<string.h>
	#include<stdlib.h>
	#include<math.h>
#line 690 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 13 "1807053.l"

#line 843 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 291 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 943 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 14 "1807053.l"
{  printf("Check Equal\n"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "1807053.l"
{ printf("Check INEQUAL \n"); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 18 "1807053.l"
{ printf("LT\n"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 20 "1807053.l"
{ printf("GT\n"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 22 "1807053.l"
{ printf("LESS OR EQUAL\n"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 24 "1807053.l"
{ printf("GREATER OR EQUAL\n"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 26 "1807053.l"
{ printf("FOR Loop, Range and Increment\n"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 28 "1807053.l"
{ printf("Print Variable\n"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "1807053.l"
{ printf("Print Text String\n"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "1807053.l"
{ printf("INCLUDE Header\n"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 34 "1807053.l"
{ printf("Cosine Function\n"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 36 "1807053.l"
{ printf("Sine Function\n"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 38 "1807053.l"
{ printf("Tangent Function\n"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 40 "1807053.l"
{ printf("Maximum Number check\n"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "1807053.l"
{ printf("Minimum Number check\n"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "1807053.l"
{
                                                                                                 printf("Single Line Comment\n");
                                                                                                 char c;
                                                                                                 while(c = input() != '\n') {
                                                                                                 printf("%c", c);
                                                                                                   }
                                                                                                 printf("\n");
                                                                                            }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 53 "1807053.l"
{ printf("Integer Declaration\n"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 54 "1807053.l"
{ printf("Float Declaration\n"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "1807053.l"
{ printf("Character Declaration\n"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "1807053.l"
{ printf("Constant Declaration\n"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "1807053.l"
{ printf("SQUARE\n"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "1807053.l"
{ printf("CUBIC\n"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "1807053.l"
{ printf("MAXIMUM Check\n"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "1807053.l"
{ printf("MINIMUM Check\n"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "1807053.l"
{ printf("Conditional Statement if\n"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "1807053.l"
{ printf("Conditional Statement elif\n"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "1807053.l"
{ printf("Conditional Statement else\n"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "1807053.l"
{ printf("Loop\n"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "1807053.l"
{ printf("Loop\n"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "1807053.l"
{ printf("ASSIGNMENT\n"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "1807053.l"
{ printf("ADDITION\n"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 76 "1807053.l"
{ printf("SUBTRACTION\n"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 78 "1807053.l"
{ printf("MULTIPLICATION\n"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 80 "1807053.l"
{ printf("DIVISION\n"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 82 "1807053.l"
{ printf("EXPONENTIATION\n"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 84 "1807053.l"
{ printf("INCREMENT\n"); }   
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 86 "1807053.l"
{ printf("DECREMENT\n"); }  
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 88 "1807053.l"
{ printf("LESS THAN\n"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 90 "1807053.l"
{ printf("GREATER THAN\n"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 92 "1807053.l"
{ printf("LESS THAN OR EQUAL\n"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 94 "1807053.l"
{ printf("GREATER THAN OR EQUAL\n"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 96 "1807053.l"
{ printf("Check Equality\n"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 98 "1807053.l"
{ printf("Check Inequality\n"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 100 "1807053.l"
{ printf("AND Operator\n"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 102 "1807053.l"
{ printf("OR Operator\n"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 104 "1807053.l"
{ printf("NOT Operator\n"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 107 "1807053.l"
{ printf("Opening Bracket\n"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 109 "1807053.l"
{ printf("Closing Bracket\n"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "1807053.l"
{ printf("Opening Parenthesis\n"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 113 "1807053.l"
{ printf("Closing Parenthesis\n"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 115 "1807053.l"
{ printf("Opening Bracket\n"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 117 "1807053.l"
{ printf("Closing Bracket\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 119 "1807053.l"
{ printf("Semicolon\n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 121 "1807053.l"
{ printf("VARIABLE\n"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 123 "1807053.l"
{ printf("FLOAT Point Value\n"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 125 "1807053.l"
{ printf("NUM\n"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 127 "1807053.l"
{ printf("\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 128 "1807053.l"
{}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 130 "1807053.l"
ECHO;
	YY_BREAK
#line 1228 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 291 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 291 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 290);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 130 "1807053.l"


int yywrap() {
    return 1;
}

int main() {
    yyin = freopen("in.txt", "r", stdin);
    yyout = freopen("out.txt", "w", stdout);
    yylex();
    return 0;
}